rootUrl: http://static.dev.sparebank1.no:81/examples/
gridUrl: 'overidden by test script to point towards dockerized browser'
screenshotsDir: './visual-tests/baseline-screenshots'
browsers:
  firefox:
    windowSize: 1030x1080
    desiredCapabilities:
      browserName: firefox

