

static-webserver:
  image: ***REMOVED***/dev-static-files/master
  environment:
    - DOMAIN_NAME=***REMOVED***
  volumes:
    - ./examples:/var/www/static


webdriver:
  image: selenium/standalone-firefox
  links:
    - static-webserver:***REMOVED***
  ports:
    - 4444
