

static-webserver:
  image: docker.intern.sparebank1.no/dev-static-files/master
  environment:
    - DOMAIN_NAME=static.dev.sparebank1.no
  volumes:
    - ./examples:/var/www/static


webdriver:
  image: selenium/standalone-firefox
  links:
    - static-webserver:static.dev.sparebank1.no
  ports:
    - 4444
