rootUrl: http://static.dev.sparebank1.no:81/example/
gridUrl: 'overidden by test script to point towards dockerized browser'
screenshotsDir: './visual-tests/baseline-screenshots'
browsers:
  firefox-small:
    windowSize: 479x10000
    desiredCapabilities:
      browserName: firefox
  firefox-medium:
    windowSize: 768x10000
    desiredCapabilities:
      browserName: firefox
  firefox-large:
    windowSize: 1025x10000
    desiredCapabilities:
      browserName: firefox
