name: Publish GitHub pages

on:
    push:
        workflow_dispatch:

jobs:
    publish:
        name: Build and publish GitHub pages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: '0'
                  ref: 'main'

            - name: git config user
              run: |
                  git config user.email "designsystem@sparebank1.no"
                  git config user.name "sb1-designsystem"

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  registry-url: 'https://registry.npmjs.com'

            - run: |
                  npm install
                  npm run build
                  npm run ghpages

            - name: Deploy gh-pages
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  folder: component-overview/build/
                  branch: gh-pages
                  token: ${{ secrets.GH_USER_PAT }}
